export const flags ={
        MEX:require('../assets/jogos/mexico.png'),
        RSA:require('../assets/jogos/south africa.png'),
        KOR:require('../assets/jogos/south korea.png'),
        CZE:require('../assets/jogos/czech republic.png'),
        CAN:require('../assets/jogos/canada.png'),
        ESP:require('../assets/jogos/spain.png'),
        NED:require('../assets/jogos/netherlands.png'),
        BIH:require('../assets/jogos/bosnia and herzegovina.png'),
        ITA:require('../assets/jogos/italy.png'),
        JPN:require('../assets/jogos/japan.png'),
        BRA:require('../assets/jogos/brazil.png'),
        POR:require('../assets/jogos/portugal.png'),
        FRA:require('../assets/jogos/france.png'),
        ARG:require('../assets/jogos/argentina.png'),
        GER:require('../assets/jogos/germany.png'),
        ENG:require('../assets/jogos/england.png'),
        PAR:require('../assets/jogos/paraguay.png'),
        HAI:require('../assets/jogos/haiti.png'),
        SCO:require('../assets/jogos/scotland.png'),
        USA:require('../assets/jogos/usa.png'),
        AUS:require('../assets/jogos/australia.png'),
        GHA:require('../assets/jogos/ghana.png'),
        IRN:require('../assets/jogos/iran.png'),
        TUR:require('../assets/jogos/turkey.png'),
        MAR:require('../assets/jogos/morocco.png'),
        CIV:require('../assets/jogos/ivory coast.png'),
        RUS:require('../assets/jogos/russia.png'),
        QAT:require('../assets/jogos/qatar.png'),
        SUI:require('../assets/jogos/switzerland.png'),
        BEL:require('../assets/jogos/belgium.png'),
        CRO:require('../assets/jogos/croatia.png'),
        ECU:require('../assets/jogos/ecuador.png'),
        CUW:require('../assets/jogos/curacao.png'),
        SWE:require('../assets/jogos/sweden.png'),
        DEN:require('../assets/jogos/denmark.png'),
        NIG:require('../assets/jogos/nigeria.png'),
        TUN:require('../assets/jogos/tunisia.png'),
        KSA:require('../assets/jogos/saudi arabia.png'),
        URU:require('../assets/jogos/uruguay.png'),
        GRC:require('../assets/jogos/greece.png'),
        CPV:require('../assets/jogos/cabo verde.png'),
        NZL:require('../assets/jogos/new zealand.png'),
        EGY:require('../assets/jogos/egypt.png'),
        SEN:require('../assets/jogos/senegal.png'),
        IRQ:require('../assets/jogos/iraq.png'),
        NOR:require('../assets/jogos/norway.png'),
        AUT:require('../assets/jogos/austria.png'),
        JOR:require('../assets/jogos/jordan.png'),
        GUA:require('../assets/jogos/guatemala.png'),
        ALB:require('../assets/jogos/albania.png'),
        PAN:require('../assets/jogos/panama.png'),
        COD:require('../assets/jogos/ivory coast.png'),
        COL:require('../assets/jogos/colombia.png'),
        VEN:require('../assets/jogos/venezuela.png'),
        LBN:require('../assets/jogos/lebanon.png'),
        ALG:require('../assets/jogos/argelia.png'),
        UZB:require('../assets/jogos/uzbekistao.png'),
};
